trigger:
  batch: true
  branches:
    include:
    - master
    - azure

pr:
- master

jobs:
- job: common_build_linux
  displayName: 'Common Build (Linux)'
  pool:
    vmImage: ubuntu-16.04
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '8.12'
      displayName: 'Install - Node.js 8.12'
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '2.7'
        architecture: 'x64'
      displayName: 'Install - Python 2.7'
    - bash: git --version && node --version && python --version && yarn --version
      displayName: 'Prerequisites - Print Versions'
    - bash: yarn
      displayName: 'Build'
    - bash: yarn test
      displayName: 'Test'
