name: Build

on:
  push:
    branches:
      - master
      - gh-actions # TODO: remove this.
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 4 * * *' # Runs every day at 4am: https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events-schedule

jobs:

  build:
    name: ${{ matrix.os }}, Node.js v${{ matrix.node }}, Python ${{ matrix.python }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node: ['12.x']
        python: ['2.x']
        include:
          - os: ubuntu-latest
            node: '12.x'
            python: '3.x'
            tests: 'skip'

    runs-on: ${{ matrix.os }}
    timeout-minutes: 60

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'

      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Build
        shell: bash
        run: |
          yarn --skip-integrity-check
          npx electron-replace-ffmpeg
          npx electron-codecs-test
          ./scripts/check_git_status.sh
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9

      - name: Test (headless)
        if: matrix.tests != 'skip'
        shell: bash
        run: |
          yarn test:theia

      - name: Test (browser)
        if: matrix.tests != 'skip' && matrix.os == 'ubuntu-latest'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:browser

      - name: Test (electron)
        if: matrix.tests != 'skip' && matrix.os == 'ubuntu-latest'
        uses: GabrielBB/xvfb-action@v1
        with:
          run: yarn test:browser

  publish:
    needs: build
    if: github.ref == 'refs/heads/master' && github.event_name != 'schedule'
    runs-on: ubuntu-latest

    # The current approach is silly. We should be smarter and use `actions/upload-artifact` and `actions/download-artifact` instead of rebuilding
    # everything from scratch again. (git checkout, Node.js install, yarn, etc.) It was not possible to share artifacts on Travis CI without an
    # external storage (such as S3), so we did rebuild everything before the npm publish. We should overcome this limitation with GH Actions.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '2.x'

      - name: Publish
        run: |
          yarn --skip-integrity-check
          yarn docs
          yarn publish:next
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # https://github.com/microsoft/vscode-ripgrep/issues/9
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} # The variable name comes from here: https://github.com/actions/setup-node/blob/70b9252472eee7495c93bb1588261539c3c2b98d/src/authutil.ts#L48

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages
